---
configuration:
    name: Network Bandwidth
    description: Benchmark testing network bandwidth over a time using iperf
    directory: network_bandwidth
    cron: "0 * * * *"
    instance-number: 2
    instance-types:
      - c8g.metal-24xl
      - c7gn.metal
      - c7g.metal
      - c7i.metal-24xl
      - c7a.metal-48xl
      - c5.metal
      - c6g.medium
      - t2.micro

      - c7g.large
      - c7g.xlarge
      - c7g.2xlarge

nodes:
  - node-id: 0
    ansible-configuration: ansible.yml

  - node-id: 1
    benchmark-command: ./run_bandwidth.sh
    output-command: python3 format_output.py results_1.txt results_2.txt

  - node-id: 2
    benchmark-command: timeout 420 iperf -s
    instance-type: c7gn.metal

plots:
  - type: line
    title: Network Bandwidth over Time
    xaxis: Time [s]
    yaxis: Network Bandwidth [Gbit/s]
    series:
      - x: intervals_first_attempt
        y: connection_min_first_attempt
        legend: Minimum Connection Bandwidth

      - x: intervals_first_attempt
        y: connection_avg_first_attempt
        legend: Average Connection Bandwidth

      - x: intervals_first_attempt
        y: connection_max_first_attempt
        legend: Maximum Connection Bandwidth

      - x: intervals_first_attempt
        y: sum_bandwidth_first_attempt
        legend: Connections Sum
