configuration:
  name: "Cache latency"
  description: "Benchmark analyzing the basic properties of the CPU cache"
  directory: cache_latency
  cron: "0 * * * *"
  instance-number: 1
  instance-types:
#    - c8g.metal-24xl
#    - c7gn.metal
#    - c7i.metal-24xl
#    - c7a.metal-48xl

#    - a1.metal
#    - a1.2xlarge
#    - a1.medium
#
#    - c7g.metal
#    - c7g.2xlarge
#    - c7g.medium
#
#    - c5.metal
#    - c5.2xlarge
#    - c5.large
#
#    - c7i.metal-24xl
#    - c7i.2xlarge
#    - c7i.large
#
#    - c7a.metal-48xl
#    - c7a.2xlarge
    - c7a.large

#    - m5a.24xlarge
#    - m5a.2xlarge
#    - m5a.large

nodes:
  - node-id: 0
    ansible-configuration: ansible.yml
    benchmark-command: ./run_latency.sh
    output-command: python3 format_output.py results.csv
plots:
  - type: line
    title: Cache latency for different input sizes
    xaxis: Input size [10^x MB]
    yaxis: Latency [ns]
    series:
      - x: input_size_log10
        y: latency
        legend: Latency
