configuration:
  name: "Cache latency"
  description: "Benchmark analyzing the basic properties of the CPU cache"
  directory: cache_latency
  cron: "0 * * * *"
  instance-number: 1
  instance-types:
    - c8g.metal-24xl
    - c7gn.metal
    - c7g.metal
    - c7i.metal-24xl
    - c7a.metal-48xl
    - c5.metal

nodes:
  - node-id: 0
    ansible-configuration: ansible.yml
    benchmark-command: ./run_latency.sh
    output-command: python3 format_output.py results.txt
plots:
  - type: line
    title: Cache throughput for different input sizes
    xaxis: Input size [MB]
    yaxis: Cache throughput [GB/s]
    series:
      - x: input_size
        y: throughput_gb_s
        legend: Throughput

  - type: line
    title: Cache latency for different input sizes
    xaxis: Input size [MB]
    yaxis: Latency [ns]
    series:
      - x: input_size
        y: latency
        legend: Latency

  - type: line
    title: Processing time for different input sizes
    xaxis: Input size [MB]
    yaxis: Processing Time [ns]
    series:
      - x: input_size
        y: time_ns
        legend: Processing time
