---
configuration:
    name: "Memory Bandwidth"
    description: "Benchmark testing Memory Bandwidth for different number of threads"
    directory: memory_bandwidth
    cron: "0 * * * *"
    instance-number: 1
    instance-types:
      # Graviton
      - c6g.medium
      - c6g.2xlarge
      - c6g.metal

      - c7g.metal
      - c7g.2xlarge
      - c7g.medium

      - c8g.medium
      - c8g.2xlarge
      - c8g.metal-24xl

      # Intel
      - c5.metal
      - c5.2xlarge
      - c5.large

      - c6i.metal
      - c6i.2xlarge
      - c6i.large

      - c7i.metal-24xl
      - c7i.2xlarge
      - c7i.large

      # AMD
      - m5a.24xlarge
      - m5a.2xlarge
      - m5a.large

      - c5a.24xlarge
      - c5a.2xlarge
      - c5a.large

      - c6a.metal
      - c6a.2xlarge
      - c6a.large

      - c7a.metal-48xl
      - c7a.2xlarge
      - c7a.large

nodes:
  - node-id: 0
    ansible-configuration: ansible.yml
    benchmark-command: ./run_membw.sh
    output-command: python3 format_output.py results.csv

plots:
  - type: line
    title: Bandwidth depending on number of threads
    xaxis: Threads count
    yaxis: Memory Bandwidth [GB/s]
    series:
      - x: thread_counts
        y: memory_bandwidth
        legend: Memory bandwidth
